### ISSUE TITLE
ActiveRecord::RecordNotUnique on bulkrax import

### ISSUE THREAD

**Issue by jwellnit** [LafayetteCollegeLibraries/spot#1022]
Persistent error on bulkrax branches involving default values for namespace. Error seemingly happens at random and can affect any number of items in a bulk import. Error text below:

Error: ActiveRecord::RecordNotUnique - PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_minter_states_on_namespace" DETAIL: Key (namespace)=(default) already exists. : INSERT INTO "minter_states" ("template", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"

Items not affected with this issue, including in batches where some objects were, have a correctly generated noid

**Comment by jwellnit** [comment]
Potential issue, the import process moves on before the process of noid generation is complete, possibly an issue with the bulkrax csv parser

**Comment by rococodogs** [comment]
pretty sure this was fixed with #1105? lmk if not
