### ISSUE TITLE
mapper metadata profile audit

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#124]
it occurred to me that i missed the `notes` field being migrated to `description` in the shakespeare mapper (and magazine i think?) so an across-the-board audit would be a good idea

**Comment by malantonio** [comment]
see https://gist.github.com/malantonio/cb064a20217c51bce5cf41fc9d5647b3 for run down of sources, properties, and some notes

**Comment by malantonio** [comment]
hey @noraegloff, just wanted some clarification after running through the data model:

## subtitle

>  Map from <titleInfo_subTitle> AND <titleInfo_partName> in Shakespeare Bulletin MODS data.

are we combining the two fields into one value? or should each be an individual value (a lot of records have a value for each of those fields)

## rights holder

> Prior to migration, Rights Holder attributions will be retroactively applied at the item or collection level.

is this still in process?

**Comment by noraegloff** [comment]
> ## subtitle
> > Map from <titleInfo_subTitle> AND <titleInfo_partName> in Shakespeare Bulletin MODS data.
> 
> are we combining the two fields into one value? or should each be an individual value (a lot of records have a value for each of those fields)

Thanks for confirming: these 2 mapped properties should each be an individual value in subtitle. 


> ## rights holder
> > Prior to migration, Rights Holder attributions will be retroactively applied at the item or collection level.
> 
> is this still in process?

Yes, it is: I will update the model to reflect the fact that work for this is ongoing.  At this point in time I feel most comfortable saying that assigning Rights Holder information to records will be a post-migration enhancement. I will holler if that changes and I am able to evaluate Rights Holder status and then generate values for collections in this model.
