### ISSUE TITLE
update europeana rights-reserved license?

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#140]
see: https://www.europeana.eu/portal/en/rights/rr-r.html

> This rights statement has been RETIRED from use by Europeana. Please consult the available rights statements for all available options.

@noraegloff thoughts on this?

**Comment by noraegloff** [comment]
I believe that Europeana retired all the "Rights Reserved -- xx" statements some time ago. As far as I can recall that was never one of the 14 available from Europeana (plus the 6 that Janna added as a supplement, which are in the usage notes in the Model) that we were planning to put in our local list anyway. 

Are you trying to set a Rights Statement policy in the repository for items that are restricted off campus or in some other way? [No Copyright - Other Known Legal Restriction (NoC-OKLR](http://rightsstatements.org/vocab/NoC-OKLR/1.0/)) could be an option there.

**Comment by malantonio** [comment]
ahh okay. i'm not entirely sure how i got this list, but from 69d334b06 it looks like i replaced the default hyrax rights with a list from somewhere (?). i'll go through and clean that up.

thanks!

**Comment by noraegloff** [comment]
Ok, here is the official list from Europeana: https://pro.europeana.eu/page/available-rights-statements
