### ISSUE TITLE
need content for textual pages

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#187]
- About page
- Help/Usage page
- ~Welcome tagline~ (see a1400c8)

**Comment by noraegloff** [comment]
@malantonio I have written up some text for these pages in [the Google doc](https://docs.google.com/document/d/15A7HP7jqAG4pcPSDBy_0HkFuwPGhcUYkSYc-dn-Wnc4/edit#heading=h.fxp1avl3sgh6) you made :)

**Comment by noraegloff** [comment]
hey @malantonio - I updated the [LDR Text Content google doc](https://docs.google.com/document/d/15A7HP7jqAG4pcPSDBy_0HkFuwPGhcUYkSYc-dn-Wnc4/edit#) help text and screenshots to reflect the new download options for items; also created a '[Report a Problem](https://forms.gle/t1KG8cgGvLFrXNp1A)' google form that is linked from that document.
