### ISSUE TITLE
build a collections#index view

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#282]
we currently don't have a way of browsing items based on collections (the link on the homepage directs users to the dss.laf/collections page). since the collections_controller doesn't implement an `#index` method, we could use this to land users on a `has_model_ssim:Collection` search.

**Comment by malantonio** [comment]
removed from the 2019.1 milestone as we've built a kind of stop-gap measure of linking to a faceted search on the `has_model_ssim` field (see 9e9b7bb)

**Comment by rococodogs** [comment]
closed with #645
