### ISSUE TITLE
Sort by: Issue Date is broken

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#319]
![Screen Shot 2019-10-31 at 11 24 06 AM](https://user-images.githubusercontent.com/38009796/67961357-ffcef280-fbd1-11e9-815d-1b0e069e8e60.png)

Items are displayed in seemingly random order when user attempts to Sort by: Issue Date.  This happens regardless of whether items of being browsed by collection, or as results from a search.

**Comment by malantonio** [comment]
looks like it's pointing at a field that we've never indexed to: https://github.com/LafayetteCollegeLibraries/spot/blob/master/app/controllers/catalog_controller.rb#L251-L252 😨
