### ISSUE TITLE
issues with existing tiffs

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#440]
# errors

these errors prevent items from being ingested into the repository (`convert` and `identify` exit with a `1` code)

## cpw-nofuko
```
identify: Wrong data type 3 for "PixelXDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/820.
identify: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/820.
identify: Sanity check on directory count failed, this is probably not a valid IFD offset. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/560.
identify: Failed to read custom directory at offset 52446. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/560.
```

### affected collections
- cpw-nofuko
- cpw-shashinkai
- lewis-postcards (backs are jpgs + unaffected)
- mdl-prints

--------

# warnings

items from these collections will ingest but will display warnings

## `Incompatible type for "RichTIFFIPTC"`

`convert` works, but this warning is displayed:

```
identify: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/1036.
```

### affected collections

- alsace-images
- geology-slides
- imperial-postcards (backs are jpg + unaffected)
- mammana-postcards (front + back scans)
- pacwar-postcards (front + back scans)
- tjwar-postcards (front + back scans)
- warner-negs-indonesia
- warner-negs-manchuria (also affects "submerged" tifs)
- warner-slides-japan
- warner-souvenirs
- woodsworth-images

## `Wrong data type 3 for "PixelXDimension" (or "PixelYDimension")`

`convert` works, but these warnings are displayed:

```
identify: Wrong data type 3 for "PixelXDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1036.
identify: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1036.
identify: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1036.
```

### affected collections

- pa-koshitsu
- pa-omitsu01 (backs are jpgs and unaffected)
- pa-omitsu02 (backs are jpgs and unaffected)
- pa-omitsu03 (backs are jpgs and unaffected)
- pa-tsubokura

**Comment by rococodogs** [comment]
we've updated the ingest workflow to consist of:
- copy source files locally
- batch process in photoshop to open and re-save as a TIFF (which strips away the errors, but usually leaves the warnings intact)
- bag the converted files + proceed as usual
