### ISSUE TITLE
add Research Assistance to the Image metadata display

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#462]
It looks like values from ye olde 'contributor' property have successfully been mapped into the new 'Research Assistance' property, because I can see them in the item edit form on stage.  However, the public view of the item does not display this property at all.  

Collections affected: gc-iroha01, pa-omitsu03, pa-omitsu02, pa-omitsu01, pa-koshitsu, lewis-postcards, pacwar-postcards.

**Comment by malantonio** [comment]
do we want this visible to all users? or just staff?

**Comment by noraegloff** [comment]
@malantonio this should be a public property visible to all users: Looking at the collections on digital.laf, this has been a publicly visible bit of metadata.

**Comment by malantonio** [comment]
closed with #472
