### ISSUE TITLE
IIIF viewer not displaying full image

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#476]
In some collections, IIIF universal viewer is displaying only a small section of the image canvas, zoomed in.  In each case it is only displaying a tile in the upper left hand corner of the image. 

Collections affected: pa-omitsu03, pa-omitsu-02, pa-omitsu01, pa-koshitsu. 

Example screenshot from pa-omitsu03, id=[eaic:oc0031]: 
![EAICoc0031_error](https://user-images.githubusercontent.com/38009796/79376434-2be3f300-7f28-11ea-8c4c-afcaab407b77.png)

Example from pa-omitsu02, id=[eaic:ob0031]:
![EAICob0031_error](https://user-images.githubusercontent.com/38009796/79377022-0f948600-7f29-11ea-99c7-45b58eed7904.png)

Example from pa-omitsu01, id=[oa0086]:
![EAICoa0086_error](https://user-images.githubusercontent.com/38009796/79377244-5da98980-7f29-11ea-895b-24ca38142666.png)

Example from pa-koshitsu, id=[ia0012]:
![EAICia0012_error](https://user-images.githubusercontent.com/38009796/79377321-7dd94880-7f29-11ea-8529-204bc0a8c868.png)

**Comment by malantonio** [comment]
closing this for now. i think adding a photoshop re-save to our bagging process fixed this issue. feel free to re-open if you run into this again!
