### ISSUE TITLE
lewis-postcards missing some metadata

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#531]
lewis-postcards is missing some metadata values from the csv:

- **keyword** needs to be mapped in from the **keyword** column
-  **original item extent** needs to be mapped in from the **format.extent** column
- **date** needs to be be mapped from **date.artifact.lower** AND **date.artifact.upper** columns (as a single value, in an EDTF range)

**Comment by rococodogs** [comment]
double checked and it looks like the mapper code should include both "keyword" and "relation.ispartof" for the `keyword` field. my best guess is the Lewis batch was ingested _before_ the PR that updated `keyword` was pushed to stage (diff here: https://github.com/LafayetteCollegeLibraries/spot/commit/ee2014f1defb78905639b171e8ce2ca01ba063a3#diff-4898919cb14711b1e3fa72c6363a2c76)
