### ISSUE TITLE
cap missing some metadata on stage

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#590]
In cap, there are a few fields that are missing data:
   1. **description** data should be mapped in from the **description** column in the csv
   2. **subject** data should be mapped in from the **subject.LOC** column in the csv
   3. **keyword** data should be mapped in from the **keyword** column in the csv
   4. **note** data should be mapped in from the **format.digital** column in the csv

**Comment by rococodogs** [comment]
blah! ingested the batch on 2020-05-08, with a first pass mapper. but then:
- keyword was fixed as part of the initial PR (see 9fcffbbe7)
- fixed **description** and **subject** with #540
- fixed **note** with #555
