### ISSUE TITLE
mdl-prints missing some metadata

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#595]
In mdl-prints, there are some properties that didn't get populated:
   1. Missing **donor** data, this should be mapped in from **description.provenance** in the csv. 
   2. Missing **rights.statement** data, this should be mapped in from **rights.statement** in the csv. 
   3. Missing **subject** data, this should be mapped in from **subject.lcsh** in the csv. 
   4. Missing **note** data, this should be mapped in from **format.digital** in the csv.

**Comment by rococodogs** [comment]
looks like the same situation as with cap (see #590):

- donor, rights_statement, and subject were fixed with #524
- note was fixed with #555

ingested the collection before the fixes, forgot to reingest some afterwards
