### ISSUE TITLE
stuff values into geology-slides source and publisher

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#614]
There are two sources for the geology-slides collection: the metadata comes from _Guidebook to Earth Science Slides_ by John S. Shelton, and the images come from the Crystal Productions 2004 CD-ROM set. [According to OCLC](http://www.worldcat.org/oclc/71832286) these were published/packaged together as a set. 

Although this will definitely be explained in the collection description, it should also be expressed by item level metadata especially since there is an active copyright. 

Values for all items in geology slides should be: 
      **source**: Shelton, John S. Earth Science Slides. Glenview, Ill: Crystal Productions, 2004. 
      **publisher**: Crystal Productions

**Comment by rococodogs** [comment]
<img width="1145" alt="Screen Shot 2020-11-10 at 3 43 46 PM" src="https://user-images.githubusercontent.com/2744987/98732924-c943c000-236d-11eb-9ae5-eabaa4381d6e.png">

fixed on production 🎉
