### ISSUE TITLE
display ordering of mdl-prints subcollections is wonky

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#618]
When viewing the collection landing page for mdl-prints, the subcollections are displayed out of order. 

Screenshots: 
<img width="989" alt="Screen Shot 2020-10-12 at 2 48 45 PM" src="https://user-images.githubusercontent.com/38009796/95780915-d1d7a680-0c9a-11eb-9bb6-b43c77aeafcd.png">
<img width="563" alt="Screen Shot 2020-10-12 at 2 51 53 PM" src="https://user-images.githubusercontent.com/38009796/95780917-d2703d00-0c9a-11eb-90f5-acfa656a2c4f.png">
<img width="554" alt="Screen Shot 2020-10-12 at 2 52 02 PM" src="https://user-images.githubusercontent.com/38009796/95780918-d2703d00-0c9a-11eb-93d4-0f36df886023.png">

**Comment by rococodogs** [comment]
this is happening because we're sorting the subcollections by title, and as strings "10" sorts before "2". our best bet might be to add leading zeros for collections < 10, ex "Marquis de Lafayette Prints Series 01".

**Comment by noraegloff** [comment]
oh derp of course, thank you. I just added the leading zeroes and will close this issue.
