### ISSUE TITLE
workflow for student work submission

### ISSUE THREAD

**Issue by rococodogs** [LafayetteCollegeLibraries/spot#769]
this can be a working document for this to get hammered out

1. work is submitted by student
2. faculty member listed as "Advisor" is notified to approve submission
3. faculty member performs an action:
  a. ~faculty member rejects submission, student is notified~
  b. faculty member sends request for corrections, student is notified.
  c. faculty member approves submission, library staff in "student work approval" role is notified
4. library staff, in "student work approval" role, performs an action:
  a. ~library staff rejects submission, faculty and student are notified~
  b. library staff sends request for corrections, student is notified. (note: this may require involving the faculty member, which we might not want to do.)
  c. library staff approves submission. student and faculty member are notified by email

**Comment by rococodogs** [comment]
might be worth mentioning: we can collect/require comments on each action (faculty/lib approve/reject) and have that sent along with the message. i _believe_ they're persisted to the database, so we'll have a record.

**Comment by noraegloff** [comment]
some initial questions/thoughts: 
    1. will the submission form be directly in the LDR and linked to from a "how-to" or "student theses" page on the Library or DSS wordpress sites? so student user navigation would be **wordpress page link/button** > **ldr** > **log-in to repo via CAS** > **form** ?
    2. should library staff in "student work approval" role be able to perform corrections/edits themselves, or only approve/deny/request corrections on a work? 
    3. is there any way for admins to view submitted works that are pending "Advisor" approval, such as in the **Tasks** > **Review Submissions** panel? I'm imagining a scenario where faculty lose/miss/ignore/misunderstand thesis approval and may need a follow up, for example
    4. will loaded students and faculty user accounts have the same user roles by default (e.g. depositor) or two different ones?

**Comment by rococodogs** [comment]
@noraegloff 

1. if we link directly to the new StudentWork form and a student isn't logged in, it'll redirect them to CAS and redirect to the form on success. we might also want to add a "Add a work" link in the header dropdown for users? the workflow of **LDR Home > Dashboard > Works > Add New Work** is a little laborious.
2. i'm kind of leaning towards "yes, library staff should be able to perform edits during the process," as i'm assuming the folks we're having approve would already have admin edit access, which would give them those permissions
3. we're able to "cc" other users/groups in the form config, so we can add the library staff to that field. i'm not 100% sure what gets tasks into the "Review Submissions" panel, but it might be that
4. i'm kind of thinking we'll give students a user role of `:student` which we'll restrict to creating just new `StudentWork` objects. we should be able to do this using a released CAS attribute. we might be able to get around having to assign faculty members a user role for this, since the workflow uses Sipity roles which are independent of the app's User roles (see **LDR Home > Dashboard > Configuration > Workflow Roles**)
