### ISSUE TITLE
mint handles for every item, regardless of visibility

### ISSUE THREAD

**Issue by rococodogs** [LafayetteCollegeLibraries/spot#790]
right now, it looks like we're minting Handles for public items. we should probably mint for every item and let auth do the delegating

**Comment by noraegloff** [comment]
+1 that we should be minting handles/permalinks for all items regardless of visibility.  

A predictable use case implicating this would be adding items to a collection and editing their descriptions incrementally on private, then switching visibility to public once the collections are complete and approved by relevant stakeholders.

**Comment by rococodogs** [comment]
update on this: looks like running `Spot::HandleService.new(work).mint` on a work without a Handle will actually mint one, regardless of visibility. that's making me suspect that where the ball is being dropped is either in the actor stack (resulting in the MintHandleJob not being enqueued) or the MintHandleJob (which is just a wrapper for the above command) somehow failing. my gut is suspecting the actor stack, which has been known to let things fall through the cracks without notice.
