### ISSUE TITLE
add 'submit student work' button to navbar

### ISSUE THREAD

**Issue by noraegloff** [LafayetteCollegeLibraries/spot#885]
(In place of semi-functional Advanced Search button?) 

For ease of use and way-finding, add a 'submit student work' button to navbar, which upon clicking would direct a user to CAS and then to the form for adding a student work.  This would make directing students to the task much simpler than, for example, sending them to a library webpage which links out to the form somewhere 500 words into its content.

<img width="764" alt="Screen Shot 2022-03-30 at 11 39 18 AM" src="https://user-images.githubusercontent.com/38009796/160875286-b84ad85e-200b-4d7c-afd3-80f02c15d462.png">

**Comment by rococodogs** [comment]
after chatting, i think we're going to try to add a bar with buttons ("submit your thesis", "learn more") above the "featured collections" block, and below the masthead. as a stretch goal, i'll add a feature toggle so that we don't need to have it turned on all year long
