### ISSUE TITLE
change the bag format we're expecting

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#94]
So we're currently handling (legacy) BagIt exports, which are laid out like:

```
.
├── bag-info.txt
├── bagit.txt
├── data
│   ├── 436_metadata.csv
│   ├── Barclay-TGK-vol12-2008.pdf
│   └── license.txt
├── manifest-md5.txt
├── manifest-sha1.txt
├── tagmanifest-md5.txt
└── tagmanifest-sha1.txt
```

A problem encountered (and worked around) was that the files we're attaching to works live in the same location as the metadata and license (which is a separate file that we plan to merge into the metadata on ingest). The naming of the metadata file is also inconsistent (the IDs of LDR items was used for those legacy exports; newspapers/magazines/shakespeare-bulletins all use `metadata.csv`.  The CSV files are also laid out vertically as two columns (`key,value`), rather than two rows horizontally.

I'd like to use something more akin to this:

```
.
├── bag-info.txt
├── bagit.txt
├── data
│   ├── files
│   │   └── Barclay-TGK-vol12-2008.pdf
│   ├── license.txt
│   └── metadata.csv
├── manifest-md5.txt
├── manifest-sha1.txt
├── tagmanifest-md5.txt
└── tagmanifest-sha1.txt
```

it's not a seismic shift, but should be documented somewhere. This layout would move files into a new directory within data (`files/`) and use a horizontal `metadata.csv` file. 

Since we're doing some data cleanup before ingest, the items need to be re-bagged anyway, and I don't see these changes requiring a _lot_ of alterations.

Thoughts @noraegloff?

**Comment by noraegloff** [comment]
This sounds good to me and makes sense, no objections 👍🏻
